### ISSUE TITLE
Support of NVME devices

### ISSUE THREAD

**Issue by zen2** [d-torrance/wmhdplop#1]
Nvme devices are not supported.
Nvme devices major/minor looks like this:

crw------- 1 root root 241,  0 Nov 24 10:32 /dev/nvme0
brw-rw---- 1 root disk 259,  0 Nov 24 10:32 /dev/nvme0n1         <- device
brw-rw---- 1 root disk 259,  1 Nov 24 10:32 /dev/nvme0n1p1     <- partition
brw-rw---- 1 root disk 259,  2 Nov 24 10:32 /dev/nvme0n1p2     <- partition
brw-rw---- 1 root disk 259,  3 Nov 24 10:32 /dev/nvme0n1p3     <- partition
brw-rw---- 1 root disk 259,  4 Nov 24 10:32 /dev/nvme0n1p4     <- partition

**Comment by zen2** [comment]
This is patch that works here:

--- a/devnames.c	2007-04-20 11:17:13.000000000 +0200
+++ b/devnames.c	2016-11-24 12:59:17.405493809 +0100
@@ -153,6 +153,14 @@
       if (part_id) *part_id = 0;            
       return 9;      
 #endif
+
+#ifdef BLOCK_EXT_MAJOR
+    case (BLOCK_EXT_MAJOR):
+      if (name) sprintf(name, "nvme0n%cp%s", "0123456789"[(minor/16)], to_num_(minor));
+      if (hd_id) *hd_id = 400 + minor;
+      if (part_id) *part_id = 0;            
+      return 10;
+#endif
   }
   if (name) *name = 0;
   if (hd_id) *hd_id = -1;

**Comment by d-torrance** [comment]
Thanks for the patch!

Note that this is actually just an old copy of my repository for packing wmhdplop for Debian (the new one is at https://anonscm.debian.org/git/pkg-wmaker/wmhdplop.git).  The original authors of wmhdplop hosted everything at http://hules.free.fr/wmhdplop/.

However, they haven't released anything since 2007 and haven't responded to my requests of merging various patches from the Debian package.  So for a while I've thought of just taking over maintenance of wmhdplop under the umbrella of the Window Maker Team.  Your patch gave me the push I needed to actually do that.  :)

Anyway, it's now been pushed to the proper dockapps git repo (http://repo.or.cz/dockapps.git/commitdiff/8b074a3) and a new version of wmhdplop is available at http://www.dockapps.net/wmhdplop.

Thanks again!
